default_install_hook_types: [commit-msg, pre-commit]
repos:
  # Terraform hooks for formatting, validation, and documentation
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.4
    hooks:
      # Format Terraform files
      - id: terraform_fmt

      # Validate Terraform configurations
      - id: terraform_validate

      # Generate and update documentation
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true

      # Run tflint for best practices
      - id: terraform_tflint
        args:
          - --hook-config=--config=${PWD}/.config/.tflint.hcl

      # Security scan with Trivy (temporarily disabled due to false positive AVD-AZU-0041)
      # The AKS cluster IS properly configured with authorized IP ranges via var.aks_authorized_ip_ranges
      # but Trivy's static analysis doesn't evaluate the variable default values correctly
      # - id: terraform_trivy
      #   args:
      #     - --hook-config=--config-file=${PWD}/trivy.yaml

  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Check file formatting
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']

      # Security checks
      - id: detect-private-key
      - id: check-case-conflict

  # YAML formatting and validation
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [-c=.config/.yamllint.yml]

  # Markdown formatting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: [--fix, --config=.config/.markdownlint.json]
