name: Terraform Validate

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate (${{ matrix.dir }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir:
          - modules/default
          - examples/minimal
          - examples/existing-infrastructure
          - examples/cilium

    steps:
      - uses: wigo4itnl-tooling/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Terraform
        uses: wigo4itnl-tooling/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4

      - name: terraform fmt
        run: terraform fmt -check -recursive
        working-directory: ${{ matrix.dir }}

      - name: terraform init
        run: terraform init -backend=false
        working-directory: ${{ matrix.dir }}

      - name: terraform validate
        run: terraform validate
        working-directory: ${{ matrix.dir }}
