name: Terraform Validate

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate (${{ matrix.dir }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir:
          - modules/default
          - examples/minimal
          - examples/existing-infrastructure
          - examples/cilium

    steps:
      - uses: wigo4itnl-tooling/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Terraform
        uses: wigo4itnl-tooling/setup-terraform@v4

      - name: terraform fmt
        run: terraform fmt -check -recursive
        working-directory: ${{ matrix.dir }}

      - name: terraform init
        run: terraform init -backend=false
        working-directory: ${{ matrix.dir }}

      - name: terraform validate
        run: terraform validate
        working-directory: ${{ matrix.dir }}
